apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vantu.org.cert
spec:
  secretName: vantu.org.secret
  dnsNames:
    - vantu.org
    - api.vantu.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
