version: "3.9"  # optional since v1.27.0
services:
  vantu-backend:
    image: xuanlinhha/go-vantu-backend
    ports:
      - "3000:3000"
  vantu-frontend:
    image: xuanlinhha/gatsby-vantu-frontend
    ports:
      - "80:80"
    environment:
      - GATSBY_BACK_END_URL=http://localhost:3000
